symptoms_dict = {
    "itching": 0,
    "skin_rash": 1,
    "nodal_skin_eruptions": 2,
    "continuous_sneezing": 3,
    "shivering": 4,
    "chills": 5,
    "joint_pain": 6,
    "stomach_pain": 7,
    "acidity": 8,
    "ulcers_on_tongue": 9,
    "muscle_wasting": 10,
    "vomiting": 11,
    "burning_micturition": 12,
    "spotting_ urination": 13,
    "fatigue": 14,
    "weight_gain": 15,
    "anxiety": 16,
    "cold_hands_and_feets": 17,
    "mood_swings": 18,
    "weight_loss": 19,
    "restlessness": 20,
    "lethargy": 21,
    "patches_in_throat": 22,
    "irregular_sugar_level": 23,
    "cough": 24,
    "high_fever": 25,
    "sunken_eyes": 26,
    "breathlessness": 27,
    "sweating": 28,
    "dehydration": 29,
    "indigestion": 30,
    "headache": 31,
    "yellowish_skin": 32,
    "dark_urine": 33,
    "nausea": 34,
    "loss_of_appetite": 35,
    "pain_behind_the_eyes": 36,
    "back_pain": 37,
    "constipation": 38,
    "abdominal_pain": 39,
    "diarrhoea": 40,
    "mild_fever": 41,
    "yellow_urine": 42,
    "yellowing_of_eyes": 43,
    "acute_liver_failure": 44,
    "fluid_overload": 45,
    "swelling_of_stomach": 46,
    "swelled_lymph_nodes": 47,
    "malaise": 48,
    "blurred_and_distorted_vision": 49,
    "phlegm": 50,
    "throat_irritation": 51,
    "redness_of_eyes": 52,
    "sinus_pressure": 53,
    "runny_nose": 54,
    "congestion": 55,
    "chest_pain": 56,
    "weakness_in_limbs": 57,
    "fast_heart_rate": 58,
    "pain_during_bowel_movements": 59,
    "pain_in_anal_region": 60,
    "bloody_stool": 61,
    "irritation_in_anus": 62,
    "neck_pain": 63,
    "dizziness": 64,
    "cramps": 65,
    "bruising": 66,
    "obesity": 67,
    "swollen_legs": 68,
    "swollen_blood_vessels": 69,
    "puffy_face_and_eyes": 70,
    "enlarged_thyroid": 71,
    "brittle_nails": 72,
    "swollen_extremeties": 73,
    "excessive_hunger": 74,
    "extra_marital_contacts": 75,
    "drying_and_tingling_lips": 76,
    "slurred_speech": 77,
    "knee_pain": 78,
    "hip_joint_pain": 79,
    "muscle_weakness": 80,
    "stiff_neck": 81,
    "swelling_joints": 82,
    "movement_stiffness": 83,
    "spinning_movements": 84,
    "loss_of_balance": 85,
    "unsteadiness": 86,
    "weakness_of_one_body_side": 87,
    "loss_of_smell": 88,
    "bladder_discomfort": 89,
    "foul_smell_of urine": 90,
    "continuous_feel_of_urine": 91,
    "passage_of_gases": 92,
    "internal_itching": 93,
    "toxic_look_(typhos)": 94,
    "depression": 95,
    "irritability": 96,
    "muscle_pain": 97,
    "altered_sensorium": 98,
    "red_spots_over_body": 99,
    "belly_pain": 100,
    "abnormal_menstruation": 101,
    "dischromic _patches": 102,
    "watering_from_eyes": 103,
    "increased_appetite": 104,
    "polyuria": 105,
    "family_history": 106,
    "mucoid_sputum": 107,
    "rusty_sputum": 108,
    "lack_of_concentration": 109,
    "visual_disturbances": 110,
    "receiving_blood_transfusion": 111,
    "receiving_unsterile_injections": 112,
    "coma": 113,
    "stomach_bleeding": 114,
    "distention_of_abdomen": 115,
    "history_of_alcohol_consumption": 116,
    "fluid_overload.1": 117,
    "blood_in_sputum": 118,
    "prominent_veins_on_calf": 119,
    "palpitations": 120,
    "painful_walking": 121,
    "pus_filled_pimples": 122,
    "blackheads": 123,
    "scurring": 124,
    "skin_peeling": 125,
    "silver_like_dusting": 126,
    "small_dents_in_nails": 127,
    "inflammatory_nails": 128,
    "blister": 129,
    "red_sore_around_nose": 130,
    "yellow_crust_ooze": 131,
}


diseases_list = {
    15: "Fungal infection",
    4: "Allergy",
    16: "GERD",
    9: "Chronic cholestasis",
    14: "Drug Reaction",
    33: "Peptic ulcer diseae",
    1: "AIDS",
    12: "Diabetes ",
    17: "Gastroenteritis",
    6: "Bronchial Asthma",
    23: "Hypertension ",
    30: "Migraine",
    7: "Cervical spondylosis",
    32: "Paralysis (brain hemorrhage)",
    28: "Jaundice",
    29: "Malaria",
    8: "Chicken pox",
    11: "Dengue",
    37: "Typhoid",
    40: "hepatitis A",
    19: "Hepatitis B",
    20: "Hepatitis C",
    21: "Hepatitis D",
    22: "Hepatitis E",
    3: "Alcoholic hepatitis",
    36: "Tuberculosis",
    10: "Common Cold",
    34: "Pneumonia",
    13: "Dimorphic hemmorhoids(piles)",
    18: "Heart attack",
    39: "Varicose veins",
    26: "Hypothyroidism",
    24: "Hyperthyroidism",
    25: "Hypoglycemia",
    31: "Osteoarthristis",
    5: "Arthritis",
    0: "(vertigo) Paroymsal  Positional Vertigo",
    2: "Acne",
    38: "Urinary tract infection",
    35: "Psoriasis",
    27: "Impetigo",
}


# Mapping of similar words or phrases to our dictionary symptoms
symptom_mapping = {
    # Same mapping dictionary as before...
    "itch": "itching",
    "itchy": "itching",
    "rash": "skin_rash",
    "skin eruptions": "nodal_skin_eruptions",
    "sneezing": "continuous_sneezing",
    "shivers": "shivering",
    "feel cold": "chills",
    "pain in joints": "joint_pain",
    "pain in stomach": "stomach_pain",
    "stomach ache": "stomach_pain",
    "acid reflux": "acidity",
    "heartburn": "acidity",
    "tongue ulcers": "ulcers_on_tongue",
    "muscle loss": "muscle_wasting",
    "throw up": "vomiting",
    "burning urination": "burning_micturition",
    "blood in urine": "spotting_ urination",
    "tired": "fatigue",
    "exhausted": "fatigue",
    "gained weight": "weight_gain",
    "anxious": "anxiety",
    "cold extremities": "cold_hands_and_feets",
    "emotional swings": "mood_swings",
    "lost weight": "weight_loss",
    "restless": "restlessness",
    "lethargic": "lethargy",
    "throat patches": "patches_in_throat",
    "sugar levels": "irregular_sugar_level",
    "fever": "mild_fever",
    "high temperature": "high_fever",
    "eyes sunken": "sunken_eyes",
    "short of breath": "breathlessness",
    "cannot breathe": "breathlessness",
    "sweat": "sweating",
    "dehydrated": "dehydration",
    "cannot digest": "indigestion",
    "head hurts": "headache",
    "yellow skin": "yellowish_skin",
    "dark colored urine": "dark_urine",
    "feel sick": "nausea",
    "no appetite": "loss_of_appetite",
    "eye pain": "pain_behind_the_eyes",
    "back hurts": "back_pain",
    "constipated": "constipation",
    "abdomen pain": "abdominal_pain",
    "loose stools": "diarrhoea",
    "diarrhea": "diarrhoea",
    "yellow eyes": "yellowing_of_eyes",
    "liver failure": "acute_liver_failure",
    "fluid retention": "fluid_overload",
    "swollen stomach": "swelling_of_stomach",
    "lymph nodes": "swelled_lymph_nodes",
    "general discomfort": "malaise",
    "blurry vision": "blurred_and_distorted_vision",
    "distorted vision": "blurred_and_distorted_vision",
    "mucus": "phlegm",
    "sore throat": "throat_irritation",
    "red eyes": "redness_of_eyes",
    "sinus": "sinus_pressure",
    "stuffy nose": "congestion",
    "chest hurts": "chest_pain",
    "weak limbs": "weakness_in_limbs",
    "rapid heartbeat": "fast_heart_rate",
    "painful bowel": "pain_during_bowel_movements",
    "anal pain": "pain_in_anal_region",
    "blood in stool": "bloody_stool",
    "neck hurts": "neck_pain",
    "vertigo": "dizziness",
    "dizzy": "dizziness",
    "muscle cramps": "cramps",
    "bruised": "bruising",
    "overweight": "obesity",
    "leg swelling": "swollen_legs",
    "puffy face": "puffy_face_and_eyes",
    "enlarged throat": "enlarged_thyroid",
    "brittle nails": "brittle_nails",
    "extremity swelling": "swollen_extremeties",
    "very hungry": "excessive_hunger",
    "lips tingling": "drying_and_tingling_lips",
    "speech problems": "slurred_speech",
    "knee hurts": "knee_pain",
    "hip pain": "hip_joint_pain",
    "weak muscles": "muscle_weakness",
    "stiff neck": "stiff_neck",
    "joint swelling": "swelling_joints",
    "stiff movement": "movement_stiffness",
    "spinning": "spinning_movements",
    "balance issues": "loss_of_balance",
    "unsteady": "unsteadiness",
    "one side weak": "weakness_of_one_body_side",
    "cannot smell": "loss_of_smell",
    "bladder pain": "bladder_discomfort",
    "smelly urine": "foul_smell_of urine",
    "frequent urination": "continuous_feel_of_urine",
    "gas": "passage_of_gases",
    "internal itch": "internal_itching",
    "toxic appearance": "toxic_look_(typhos)",
    "depressed": "depression",
    "irritable": "irritability",
    "pain in muscles": "muscle_pain",
    "sensorium changes": "altered_sensorium",
    "red spots": "red_spots_over_body",
    "stomach pain": "belly_pain",
    "abnormal periods": "abnormal_menstruation",
    "skin patches": "dischromic _patches",
    "watery eyes": "watering_from_eyes",
    "increased hunger": "increased_appetite",
    "excessive urination": "polyuria",
    "family history": "family_history",
    "mucus in sputum": "mucoid_sputum",
    "rusty sputum": "rusty_sputum",
    "poor concentration": "lack_of_concentration",
    "visual problems": "visual_disturbances",
    "blood transfusion": "receiving_blood_transfusion",
    "unsterile injections": "receiving_unsterile_injections",
    "unconscious": "coma",
    "bleeding stomach": "stomach_bleeding",
    "abdomen distention": "distention_of_abdomen",
    "alcohol history": "history_of_alcohol_consumption",
    "blood in phlegm": "blood_in_sputum",
    "calf veins": "prominent_veins_on_calf",
    "heart palpitations": "palpitations",
    "painful to walk": "painful_walking",
    "pimples with pus": "pus_filled_pimples",
    "peeling skin": "skin_peeling",
    "silver dusting": "silver_like_dusting",
    "nail dents": "small_dents_in_nails",
    "nail inflammation": "inflammatory_nails",
    "blisters": "blister",
    "nose sores": "red_sore_around_nose",
    "yellow discharge": "yellow_crust_ooze",
}
